development:
  clients:
    default:
      database: mongo_development
      hosts:
      - mongodb:27017
      options:
  options:
test:
  clients:
    default:
      database: mongo_test
      hosts:
        - mongodb:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
